services:
  common:
    privileged: true
    build:
      context: .
      platforms:
        - linux/amd64
    platform: linux/amd64
    environment:
      - VPN_USER=<username>
      - VPN_PASS=<password>
    volumes:
      - /local/path/to/your/vpn/configs:/app/ovpn/configs

# update with your preferred VPN details
  some-vpn-location:
   extends:
     service: common
   environment:
     - VPN_CONFIG=<some-vpn-location>
   ports:
      - "80:8080"


# Example configurations for multiple concurrent VPN containers
#  us-oregon:
#    extends:
#      service: common
#    environment:
#      - VPN_CONFIG=us_oregon
#    ports:
#      - "80:8080"
#
#  us-texas:
#    extends:
#      service: common
#    environment:
#      - VPN_CONFIG=us_texas
#    ports:
#      - "81:8080"