networks:
  protun-network:
    driver: bridge

# common properties shared across all vpn containers
x-common:
  &common
  privileged: true
  build:
    context: .
    platforms:
      - linux/amd64
  platform: linux/amd64
  networks:
    - protun-network
  volumes:
    - /path/to/your/configs:/app/ovpn/configs

services:
  # update with your preferred VPN details
  some-vpn-location:
    <<: *common
    env_file:
      - .env # contains VPN_USER and VPN_PASS
    environment:
      - VPN_CONFIG=some_vpn_location
    ports:
      - "80:8080"

  another-vpn-location:
    <<: *common
    env_file:
      - .env # contains VPN_USER and VPN_PASS
    environment:
      - VPN_CONFIG=another_vpn_location
    ports:
      - "81:8080"
